# Generated by Django 5.0.1 on 2024-02-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tests', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('COST', models.CharField(max_length=255)),
            ],
        ),
    ]
