# Generated by Django 4.2.9 on 2024-03-01 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='COST',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images/'),
        ),
        migrations.CreateModel(
            name='MedicineAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchS.medicine')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchS.store')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='stores',
            field=models.ManyToManyField(through='searchS.MedicineAvailability', to='searchS.store'),
        ),
    ]
