# Generated by Django 4.2.9 on 2024-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchS', '0004_hospital_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
