# Generated by Django 4.2.9 on 2024-03-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchS', '0005_hospital_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
    ]
