# Generated by Django 4.2.9 on 2024-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchS', '0007_hospital_address_hospital_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
