# Generated by Django 4.2.9 on 2024-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchS', '0008_alter_hospital_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stores',
        ),
        migrations.AddField(
            model_name='medicine',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='store_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='MedicineAvailability',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
