# Generated by Django 4.2.9 on 2024-03-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchS', '0010_alter_hospital_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='cost',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
