# Generated by Django 4.2.9 on 2024-03-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('selected_date', models.DateField()),
                ('selected_time', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('tests', models.CharField(max_length=255)),
            ],
        ),
    ]
